source "https://rubygems.org"

gem "github-pages"
gem "jekyll"
gem "jekyll-sitemap"
gem "pygments.rb"
gem "kramdown-parser-gfm"
gem "webrick"
gem "jekyll-remote-theme"
gem "jekyll-seo-tag"
gem "rake"
